### ISSUE TITLE
Incomplete scrape

### ISSUE THREAD

**Issue by treeshaker99** [elecnix/evalmtl#3]
I get the following errors after scrape-evalweb.rb. Suggestions?

C:/Users/me/evalmtl-master/lib/scraper.rb:29:in `rescue in perform_request':
 undefined method `page' for #<TypeError: Fixnum is not a String> (NoMethodError)
        from C:/Users/me/evalmtl-master/lib/scraper.rb:17:in `perform_request'
        from C:/Users/me/evalmtl-master/lib/scraper.rb:40:in `search_street'
        from C:/Users/me/evalmtl-master/lib/scraper.rb:72:in `search_street'
        from C:/Users/me/evalmtl-master/lib/scraper.rb:124:in `block in scrape'
        from C:/Users/me/evalmtl-master/lib/scraper.rb:119:in `each'
        from C:/Users/me/evalmtl-master/lib/scraper.rb:119:in `scrape'
        from scrape-evalweb.rb:5:in `<main>'

**Comment by elecnix** [comment]
You are getting an error within an error handler. I suggest modifying the error handler to avoid accessing the 'page' method of the Exception.

**Comment by treeshaker99** [comment]
Bonjour Nicolas,

Thx for the quick reply. I'm not a programmer, so my troubleshooting skills
are very limited. However, I did have better luck when I ran the
evalmtl-role2014 fork instead. My first scrape attempt seemed to run
smoothly up until it generated 2GB .dir and .pag files (Error: gdbm fatal
lseek error, whatever that means, heh). I suspect that was due to a
limitation of the 32-bit Ruby installation. I've since installed the 64-bit
Ruby and the scrape is running again, although I haven't yet reached the
2GB threshold. Fingers crossed.

I'm really hopeful that I can get this to work. I'm excited to be able to
peruse the data file and muddle through some rudimentary data analysis.

Your programming effort was greatly appreciated. Wonderful work. Thx.

**Comment by elecnix** [comment]
I will merge the 2014 branch into master, so this does not happen to other people. Thanks for the feedback!

**Comment by treeshaker99** [comment]
Well, even with 64-Bit Ruby 2.1.5 installed, the scrape died at the 2GB mark with the same <gdbm fatal: lseek error> problem. Stuck again, but still trying to troubleshoot. Don't even know if I'm on the right track. Has anyone been able to successfully scrape evalweb recently? Thx.

**Comment by elecnix** [comment]
Yeah, the error message leads more to a special-case in the data. You could add logging statements and resume the scrape.

**Comment by treeshaker99** [comment]
Unsure how to add logging statements ... my search efforts exceeded my experienc.

Tried scraping again from my Mac but this time and the address_2014.rb output file quickly ballooned to **>40GB** having only just made it through "aa" and "ab" street iterations. It would've eventually swallowed my entire drive just with the 'A' street names. Still plugging away and troubleshoot, on both platforms.
